In [1]:
import math
import numpy as np

Sigmoid function implementation

In [45]:
def sigmoid(x):
    return 1/(1 + math.exp(-x))

In [46]:
print(sigmoid(-1))

0.2689414213699951


In [4]:
def np_sigmoid(arr):
    return 1/(1+np.exp(-arr))

In [5]:
np_sigmoid(-1)

0.2689414213699951

In [9]:
x = np.array([1, 2, 3])
np_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

Gradient of the sigmoid function

In [8]:
def gradient_sigmoid(x):
    return np_sigmoid(x) * (1 - np_sigmoid(x))

In [11]:
gradient_sigmoid(x)

array([0.19661193, 0.10499359, 0.04517666])

Function to reshape image

In [17]:
def reshape_image(img):
    new_image = img.reshape(img.shape[0] * img.shape[1] * img.shape[2],1 )
    return new_image

In [13]:
image=np.array([[[0.5, 0.8],
                 [0.5, 0.8],
                 [0.5, 0.8]],

                [[0.5, 0.8],
                 [0.5, 0.8],
                 [0.5, 0.8]],

                [[0.5, 0.8],
                 [0.5, 0.8],
                 [0.5, 0.8]]])
image.shape

(3, 3, 2)

In [18]:
print("original image :",image, sep="\n")
reshaped = reshape_image(image)
print("reshaped image :",reshaped, sep="\n")

original image :
[[[0.5 0.8]
  [0.5 0.8]
  [0.5 0.8]]

 [[0.5 0.8]
  [0.5 0.8]
  [0.5 0.8]]

 [[0.5 0.8]
  [0.5 0.8]
  [0.5 0.8]]]
reshaped image :
[[0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]
 [0.5]
 [0.8]]


A function to perform normalization on an np.array

In [49]:
def normalised(x):
    mean = np.mean(x)
    std = np.std(x)

    return (x - mean) / std

In [50]:
normalised(image)

array([[[-1.,  1.],
        [-1.,  1.],
        [-1.,  1.]],

       [[-1.,  1.],
        [-1.,  1.],
        [-1.,  1.]],

       [[-1.,  1.],
        [-1.,  1.],
        [-1.,  1.]]])

A Softmax function implementation

In [38]:
def softmax(x):
    e_x = [np.e**i for i in x] # [a,b,c] -> [e^a, e^b, e^c]
    return e_x/sum(e_x)

In [39]:
x = np.array([1,3,8,9,0])

In [40]:
softmax(x)

array([2.44717283e-04, 1.80822973e-03, 2.68365087e-01, 7.29491939e-01,
       9.00264573e-05])

In [42]:
# sum of probabilities is 1 as expected
sum(softmax(x))

1.0

Comparing execution time of custom dotproduct vs np.dot

In [43]:
import time

x = np.ones(1000000)
y = np.ones(1000000)

def measure_time(func, *args):
    start = time.time()
    res = func(*args)
    print("Dot product :", res, "Time taken :", time.time() - start)

def dot_product(x, y):
    res = 0
    for i in range(len(x)):
        res += x[i] * y[i]
    return res

measure_time(dot_product, x, y)
measure_time(np.dot, x, y)

Dot product : 1000000.0 Time taken : 0.4400351047515869
Dot product : 1000000.0 Time taken : 0.0009658336639404297
